server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/customers/**
        - id: bankaccount-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/bankaccounts/**
        - id: credit-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/credits/**