server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/customers/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**